DROP TABLE AUTH_USER;;/*SkipError*/
CREATE TABLE AUTH_USER(
    ID VARCHAR(32)    COMMENT '用户ID' ,
    CODE VARCHAR(32)    COMMENT '用户代码' ,
    NAME VARCHAR(128)    COMMENT '用户名' ,
    PASSWORD VARCHAR(32)    COMMENT '密码' ,
    SALT VARCHAR(32)    COMMENT '密码盐值' ,
    AVATAR VARCHAR(32)    COMMENT '头像' ,
    ORG_ID VARCHAR(32)    COMMENT '机构' ,
    EMAIL VARCHAR(32)    COMMENT '邮件' ,
    PHONE VARCHAR(32)    COMMENT '手机号' ,
    STATUS VARCHAR(32)    COMMENT '状态' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户信息 ';;

ALTER TABLE AUTH_USER COMMENT '用户信息';;
DROP TABLE AUTH_USER_ACCOUNT;;/*SkipError*/
CREATE TABLE AUTH_USER_ACCOUNT(
    ID VARCHAR(32)    COMMENT '账号ID' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    ACCOUNT_CODE VARCHAR(32)    COMMENT '账号代号' ,
    PASSWORD VARCHAR(32)    COMMENT '账号密码' ,
    ACCOUNT_TYPE VARCHAR(32)    COMMENT '账号类型' ,
    STATUS VARCHAR(32)    COMMENT '账号状态' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户账号 ';;

ALTER TABLE AUTH_USER_ACCOUNT COMMENT '用户账号';;
DROP TABLE AUTH_USER_BEHAVIOR;;/*SkipError*/
CREATE TABLE AUTH_USER_BEHAVIOR(
    ID VARCHAR(32)    COMMENT '记录流水号' ,
    USER_ID VARCHAR(32)    COMMENT '用户号' ,
    OBJECT_TYPE VARCHAR(32)    COMMENT '关联对象类型' ,
    OBJECT_ID VARCHAR(32)    COMMENT '关联对象号' ,
    TYPE VARCHAR(32)    COMMENT '行为类型' ,
    VALUE VARCHAR(32)    COMMENT '行为数值' ,
    INTRO VARCHAR(512)    COMMENT '行为说明' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户行为 ';;

ALTER TABLE AUTH_USER_BEHAVIOR COMMENT '用户行为';;
DROP TABLE AUTH_USER_PROPERTY;;/*SkipError*/
CREATE TABLE AUTH_USER_PROPERTY(
    ID  VARCHAR(32)    COMMENT '属性ID' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    NAME VARCHAR(32)    COMMENT '属性名' ,
    VALUE VARCHAR(1024)    COMMENT '属性值' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID )
) COMMENT = '用户属性 ';;

ALTER TABLE AUTH_USER_PROPERTY COMMENT '用户属性';;
DROP TABLE AUTH_ORG;;/*SkipError*/
CREATE TABLE AUTH_ORG(
    ID VARCHAR(32)    COMMENT '机构ID' ,
    CODE VARCHAR(32)    COMMENT '机构代号' ,
    NAME VARCHAR(128)    COMMENT '机构名' ,
    FULL_NAME VARCHAR(128)    COMMENT '机构路径全称' ,
    SHORT_NAME VARCHAR(128)    COMMENT '机构简称' ,
    SORT_CODE VARCHAR(32)    COMMENT '排序代码' ,
    PARENT_ID VARCHAR(32)    COMMENT '上级机构' ,
    LEVEL VARCHAR(32)    COMMENT '机构级别' ,
    ORG_TYPE VARCHAR(32)    COMMENT '机构类型' ,
    LEADER VARCHAR(32)    COMMENT '负责人' ,
    REMARK VARCHAR(512)    COMMENT '机构说明' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '部门机构 ';;

ALTER TABLE AUTH_ORG COMMENT '部门机构';;
DROP TABLE AUTH_ORG_PROPERTY;;/*SkipError*/
CREATE TABLE AUTH_ORG_PROPERTY(
    ID VARCHAR(32)    COMMENT '属性ID' ,
    ORG_ID VARCHAR(32)    COMMENT '机构ID' ,
    NAME VARCHAR(32)    COMMENT '属性名称' ,
    VALUE VARCHAR(1024)    COMMENT '属性值' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '机构属性 ';;

ALTER TABLE AUTH_ORG_PROPERTY COMMENT '机构属性';;
DROP TABLE AUTH_USER_ROLE;;/*SkipError*/
CREATE TABLE AUTH_USER_ROLE(
    ID VARCHAR(32)    COMMENT '职责ID' ,
    ORG_ID VARCHAR(32)    COMMENT '机构ID' ,
    ROLE_ID VARCHAR(32)    COMMENT '角色ID' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    POSITION_TYPE VARCHAR(32)    COMMENT '岗位类型' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户角色 ';;

ALTER TABLE AUTH_USER_ROLE COMMENT '用户角色';;
DROP TABLE AUTH_ROLE;;/*SkipError*/
CREATE TABLE AUTH_ROLE(
    ID VARCHAR(32)    COMMENT '角色ID' ,
    CODE VARCHAR(32)    COMMENT '角色代码' ,
    SORT_CODE VARCHAR(128)    COMMENT '排序代码' ,
    NAME VARCHAR(128)    COMMENT '角色名' ,
    TYPE VARCHAR(32)    COMMENT '角色类型' ,
    IN_WORK_FLOW VARCHAR(1)    COMMENT '是否应用于工作流' ,
    STATUS VARCHAR(32)    COMMENT '角色状态' ,
    SUMMARY VARCHAR(512)    COMMENT '角色描述' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '角色信息 ';;

ALTER TABLE AUTH_ROLE COMMENT '角色信息';;
DROP TABLE AUTH_PERMIT;;/*SkipError*/
CREATE TABLE AUTH_PERMIT(
    CODE VARCHAR(128)    COMMENT '权限代码' ,
    ID VARCHAR(32)    COMMENT '权限ID' ,
    NAME VARCHAR(128)    COMMENT '权限名称' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '权限信息 自定义权限';;

ALTER TABLE AUTH_PERMIT COMMENT '权限信息';;
DROP TABLE AUTH_ROLE_PERMIT;;/*SkipError*/
CREATE TABLE AUTH_ROLE_PERMIT(
    ID VARCHAR(32)    COMMENT '流水号' ,
    ROLE_ID VARCHAR(32)    COMMENT '角色ID' ,
    PERMIT_CODE VARCHAR(32)    COMMENT '权限代码' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '角色权限 ';;

ALTER TABLE AUTH_ROLE_PERMIT COMMENT '角色权限';;
DROP TABLE AUTH_USER_PERMIT;;/*SkipError*/
CREATE TABLE AUTH_USER_PERMIT(
    ID VARCHAR(32)    COMMENT '流水号' ,
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    PERMIT_CODE VARCHAR(32)    COMMENT '权限代码' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户直接权限 ';;

ALTER TABLE AUTH_USER_PERMIT COMMENT '用户直接权限';;
DROP TABLE SIMS_COLLEGE;;/*SkipError*/
CREATE TABLE SIMS_COLLEGE(
    ID VARCHAR(32)    COMMENT '学院ID' ,
    NAME VARCHAR(128)    COMMENT '学院名称' ,
    SHORT_NAME VARCHAR(128)    COMMENT '学院简称' ,
    INTRO VARCHAR(512)    COMMENT '学院介绍' ,
    PROFESSION_NUMBER INT    COMMENT '专业个数' ,
    STUDENT_NUMBER INT    COMMENT '学生人数' ,
    PRESIDENT VARCHAR(32)    COMMENT '院长' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '学院 ';;

ALTER TABLE SIMS_COLLEGE COMMENT '学院';;
DROP TABLE SIMS_CLASS;;/*SkipError*/
CREATE TABLE SIMS_CLASS(
    COLLEGE_ID VARCHAR(32)    COMMENT '所在学院' ,
    MAJOR_ID VARCHAR(32)    COMMENT '所属专业' ,
    ID VARCHAR(32)    COMMENT '班级ID' ,
    NAME VARCHAR(128)    COMMENT '班级名称' ,
    STUDENT_NUMBER INT    COMMENT '班级人数' ,
    ADVISER VARCHAR(128)    COMMENT '辅导员' ,
    ESTAB_DATE DATE    COMMENT '成立时间' ,
    YEAR_NUMBER INT    COMMENT '学习年数' ,
    CRATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CRATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '班级 ';;

ALTER TABLE SIMS_CLASS COMMENT '班级';;
DROP TABLE SIMS_STUDENT;;/*SkipError*/
CREATE TABLE SIMS_STUDENT(
    COLLEGE_ID VARCHAR(32)    COMMENT '所在学院' ,
    CLASS_ID VARCHAR(32)    COMMENT '所在班级' ,
    ID VARCHAR(32)    COMMENT '学号' ,
    NAME VARCHAR(128)    COMMENT '学生姓名' ,
    ID_CARD_NO VARCHAR(32)    COMMENT '身份证号' ,
    ENG_NAME VARCHAR(32)    COMMENT '英文名' ,
    MOBILE_PHONE VARCHAR(32)    COMMENT '手机号' ,
    GENDER VARCHAR(32)    COMMENT '性别' ,
    BIRTH DATE    COMMENT '出生日期' ,
    AVATAR VARCHAR(32)    COMMENT '头像' ,
    HEIGHT DECIMAL(32,10)    COMMENT '身高' ,
    WEIGHT DECIMAL(32,10)    COMMENT '体重' ,
    NATION VARCHAR(32)    COMMENT '名族' ,
    POLITICAL VARCHAR(32)    COMMENT '政治面貌' ,
    MARITAL VARCHAR(32)    COMMENT '婚姻状况' ,
    DOMICILE_PLACE_PROVINCE VARCHAR(32)    COMMENT '籍贯（省） 国标行政区域代码-省级' ,
    DOMICILE_PLACE_CITY VARCHAR(32)    COMMENT '籍贯（市） 国标行政区域代码-市级' ,
    DOMICILE_PLACE_ADDRESS VARCHAR(32)    COMMENT '户籍地址' ,
    HOBBY VARCHAR(32)    COMMENT '爱好' ,
    INTRO VARCHAR(512)    COMMENT '简要介绍' ,
    PRESENT_ADDRESS VARCHAR(128)    COMMENT '居住地址' ,
    EMAIL VARCHAR(32)    COMMENT '电子邮件' ,
    ENTRY_DATE DATE    COMMENT '入学日期' ,
    STATUS VARCHAR(32)    COMMENT '状态' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '学生 ';;

ALTER TABLE SIMS_STUDENT COMMENT '学生';;
DROP TABLE SIMS_MAJOR;;/*SkipError*/
CREATE TABLE SIMS_MAJOR(
    ID VARCHAR(32)    COMMENT '专业ID' ,
    NAME VARCHAR(128)    COMMENT '专业名称' ,
    SHORT_NAME VARCHAR(128)    COMMENT '专业简称' ,
    ESTAB_DATE DATE    COMMENT '开设时间' ,
    INTRO VARCHAR(512)    COMMENT '专业介绍' ,
    TUITION_FEE VARCHAR(32)    COMMENT '学费' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '专业 ';;

ALTER TABLE SIMS_MAJOR COMMENT '专业';;
DROP TABLE SIMS_TEACHER;;/*SkipError*/
CREATE TABLE SIMS_TEACHER(
    COLLEGE_ID VARCHAR(32)    COMMENT '所在学院' ,
    ID VARCHAR(32)    COMMENT '教师编号' ,
    NAME VARCHAR(128)    COMMENT '姓名' ,
    GENDER VARCHAR(32)    COMMENT '性别' ,
    BIRTH DATE    COMMENT '出生日期' ,
    INTRO VARCHAR(512)    COMMENT '介绍' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '教师 ';;

ALTER TABLE SIMS_TEACHER COMMENT '教师';;
DROP TABLE SIMS_INSTRUCT;;/*SkipError*/
CREATE TABLE SIMS_INSTRUCT(
    ID VARCHAR(32)    COMMENT '课程号' ,
    TEACHER_ID VARCHAR(32)    COMMENT '任课老师' ,
    CLASS_ID VARCHAR(32)    COMMENT '任课班级' ,
    LESSON_ID VARCHAR(32)    COMMENT '教授课程' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '授课';;

ALTER TABLE SIMS_INSTRUCT COMMENT '授课';;
DROP TABLE SIMS_LESSON;;/*SkipError*/
CREATE TABLE SIMS_LESSON(
    ID VARCHAR(32)    COMMENT '课程号' ,
    NAME VARCHAR(128)    COMMENT '课程名' ,
    INTRO VARCHAR(512)    COMMENT '课程说明' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '课程 ';;

ALTER TABLE SIMS_LESSON COMMENT '课程';;
